CREATE TABLE users
(
  pk        BIGSERIAL   PRIMARY KEY,
  email     VARCHAR(50) NOT NULL,
  password  VARCHAR(100) NOT NULL,
  firstname VARCHAR(20) NOT NULL,
  lastname  VARCHAR(30) NOT NULL,
  admin     BOOLEAN NOT NULL DEFAULT FALSE,
  joined    TIMESTAMP NOT NULL DEFAULT NOW(),
  points    INTEGER DEFAULT 0,
  correct   INTEGER DEFAULT 0
);
